config/routes.rb
Rails.application.routes.draw do
  resources :customers

  get 'home/index'
  
  get 'home/show_next_appointment'

  resources :pets

  resources :appointments

  resources :doctors
  root 'home#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :customer
  belongs_to :pet
  
  validates_presence_of :pet_id
  validates_presence_of :customer_id
  validates_presence_of :reason_for_visit
  
  
  scope :most_recent, lambda { order("appointments.created_at DESC").limit(1) }
  
  
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
    #TODO refactor
    @customers = Customer.all.collect{|c| [c.name, c.id]}
    @pets = Pet.all.collect{|p| [p.name, p.id]}
    @doctors = Doctor.all.collect{|d| [d.name, d.id]}
  end

  # GET /appointments/1/edit
  def edit
    #TODO refactor
    @customers = Customer.all.collect{|c| [c.name, c.id]}
    @pets = Pet.all.collect{|p| [p.name, p.id]}
    @doctors = Doctor.all.collect{|d| [d.name, d.id]}
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        #TODO refactor
        @customers = Customer.all.collect{|c| [c.name, c.id]}
        @pets = Pet.all.collect{|p| [p.name, p.id]}
        @doctors = Doctor.all.collect{|d| [d.name, d.id]}
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        #TODO refactor
        @customers = Customer.all.collect{|c| [c.name, c.id]}
        @pets = Pet.all.collect{|p| [p.name, p.id]}
        @doctors = Doctor.all.collect{|d| [d.name, d.id]}
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:date_of_visit,  :customer_id, :doctor_id, :pet_id, :requires_remainder, :reason_for_visit)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_of_visit %><br>
    <%= f.text_field :date_of_visit %>
  </div>

  <div class="field">
    <%= f.label :pet_id %><br>
    <%= f.select :pet_id, options_for_select(@pets, @appointment.pet_id)%>
  </div>

  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.select :customer_id, options_for_select(@customers, @appointment.customer_id) %>
  </div>

  <div class="field">
    <%= f.label :doctor_id %><br>
    <%= f.select :doctor_id, options_for_select(@doctors, @appointment.doctor_id) %>
  </div>



  <div class="field">
    <%= f.label :requires_remainder %><br>
    <%= f.text_field :requires_remainder %>
  </div>

  <div class="field">
    <%= f.label :reason_for_visit %><br>
    <%= f.text_area :reason_for_visit %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Date of visit</th>
      <th>Pet</th>
      <th>Customer</th>
      <th>Doctor</th>
      <th>Pet</th>
      <th>Requires remainder</th>
      <th>Reason for visit</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date_of_visit %></td>
        <td><%= appointment.pet.name %></td>
        <td><%= appointment.customer.name %></td>
        <td><%= appointment.doctor.name %></td>
        <td><%= appointment.pet.name %></td>
        <td><%= appointment.requires_remainder %></td>
        <td><%= appointment.reason_for_visit %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date of visit:</strong>
  <%= @appointment.date_of_visit %>
</p>


<p>
  <strong>Pet:</strong>
  <%= @appointment.pet.name %>
</p>


<p>
  <strong>Customer:</strong>
  <%= @appointment.customer.name %>
</p>


<p>
  <strong>Doctor:</strong>
  <%= @appointment.doctor.name %>
</p>


<p>
  <strong>Requires remainder:</strong>
  <%= @appointment.requires_remainder %>
</p>


<p>
  <strong>Reason for visit:</strong>
  <%= @appointment.reason_for_visit %>
</p>



<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>